document.write('<div id="mobilemenu">'
+'<table id="mobiletable"> '
+'<tbody> '
+'<tr>'
+'<td><a href="http://students.washington.edu/edali/ussoc/">Stats Home</a>'
+'</td>'
+'</tr>' 
+'<tr>'
+'<td><a href="http://students.washington.edu/edali/ussoc/players/">Player Stats</a>'
+'</td>'
+'</tr>' 
+'<tr>'
+'<td><a href="http://students.washington.edu/edali/ussoc/teamstats.php">Team Stats</a>'
+'</td>'
+'</tr> '
+'<tr>'
+'<td><a href="http://students.washington.edu/edali/ussoc/boxscorefinder.php">Boxscore Search</a>'
+'</td>'
+'</tr> '
+'</tr> '
+'<tr>'
+'<td><a href="http://students.washington.edu/edali/ussoc/pgf.php">Player Game Finder </a>'
+'</td>'
+'</tr> '
+'</tbody>' 
+'</table>'
+'</div>')